### ISSUE TITLE
Update TLS certificates for use with `getzion.com` domain

### ISSUE THREAD

**Issue by chantzlarge** [getZION/communities#5]
**Traefik proxy documentation:**

https://doc.traefik.io/traefik/https/acme/

**Comment by chantzlarge** [comment]
current `acme.json` TLS configuration generated by traefik proxy found at:

`/tribes/docker/letsencrypt/acme.json` on `3.211.187.194` (communities.getzion.com)

```
{
  "myresolver": {
    "Account": {
      "Email": "ci@n2n2.co",
      "Registration": {
        "body": {
          "status": "valid",
          "contact": [
            "mailto:ci@n2n2.co"
          ]
        },
        "uri": "https://acme-v02.api.letsencrypt.org/acme/acct/130581967"
      },
      "PrivateKey": "<OMITTED>",
      "KeyType": "4096"
    },
    "Certificates": [
      {
        "domain": {
          "main": "communities.n2n2.chat"
        },
        "certificate": "<OMITTED>",
        "key": "<OMITTED>",
        "Store": "default"
      }
    ]
  }
```

**Comment by chantzlarge** [comment]
Previous domain name also referenced here:

https://github.com/getZION/communities/blob/5d39573eb932db498709e7d301c7d406d7b8c9eb/ops/ansible/playbooks/cluster_configs.yml

**Comment by chantzlarge** [comment]
Invoking `docker ps` on the host instance reveals the service does not appear to have been (re)started in ~3 weeks:

```
CONTAINER ID   IMAGE            COMMAND                  CREATED       STATUS       PORTS                                                                                                                                                            NAMES
e243b33c929d   tribes_tribes    "/app/n2n2-tribes"       3 weeks ago   Up 3 weeks   1883/tcp, 5000/tcp, 5002/tcp                                                                                                                                     tribes
2689d9d7e70f   traefik:v2.2.1   "/entrypoint.sh --lo…"   3 weeks ago   Up 3 weeks   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 0.0.0.0:8883->8883/tcp, :::8883->8883/tcp   tribes_reverse-proxy_1
```

which leads me to believe that the most recent configuration changes have been applied to the running service.

**Comment by chantzlarge** [comment]
Invoking `git fetch` on the host instance from within the `/tribes` directory reveals the `local` git head is 4 commits behind the `remote`:

```
ubuntu@ip-172-31-5-72:/tribes$ git status
On branch main
Your branch is behind 'origin/main' by 4 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean
```

**Comment by chantzlarge** [comment]
Considering fetching these changes, rebuilding the image locally, and restarting the [docker] process. Unaware of any potentially dangerous side-effects... @masterial any thoughts before I do so?

**Comment by masterial** [comment]
It's best to rerun the flow from scratch. These might be breaking changes.

**Comment by chantzlarge** [comment]
Working with @masterial we were able to successfully resolve the issue by doing the following:

- Upgrade the traefik proxy dependency used for provisioning the TLS/SSL certificate
- Modify the configuration—[traefik.yaml](https://github.com/getZION/communities/blob/main/docker/traefik.yaml)—to use the cloudflare provider documented [here](https://doc.traefik.io/traefik/https/acme/#providers)

**Comment by chantzlarge** [comment]
As an ancillary benefit of resolving this issue, the instance was also scaled to increase the CPU capacity required to meet the upcoming demand anticipated for the release.
